packages:
  - "apps/*"
  - "packages/*"
overrides:
  "@wdio/tauri-service>@wdio/native-utils": 2.5.0
  "mocha>serialize-javascript": 7.0.7
allowBuilds:
  edgedriver: false
  esbuild: true
  geckodriver: false
minimumReleaseAgeExclude:
  - "@vitejs/plugin-react@6.0.4"
  - html-parse-stringify@4.0.1
  - react-i18next@17.0.11
  - react-router@8.3.0
