//! Tool descriptor: metadata the shell shows for a tool.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Stable metadata describing a hosted tool.
///
/// The TypeScript mirror of this type lives in `packages/contracts`
/// (generated by ts-rs; see `docs/adr/0005-ts-rs-generated-contracts.md`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct ToolDescriptor {
    /// Unique kebab-case identifier, e.g. `boq-inspector`.
    pub id: String,
    /// Contract version the tool targets (see `TOOL_CONTRACT_VERSION`).
    pub contract_version: u32,
    /// i18n key for the tool's display name.
    pub name_key: String,
    /// i18n key for the tool's one-line description.
    pub description_key: String,
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;

    #[test]
    fn descriptor_serializes_to_camel_case_json_fields() {
        let descriptor = ToolDescriptor {
            id: "example".to_string(),
            contract_version: 1,
            name_key: "tools.example.name".to_string(),
            description_key: "tools.example.description".to_string(),
        };
        let json = serde_json::to_string(&descriptor).expect("serializes");
        assert!(json.contains("\"id\":\"example\""));
        assert!(json.contains("contract_version"));
    }

    #[test]
    fn typescript_binding_contains_all_fields() {
        let decl = ToolDescriptor::decl(&ts_rs::Config::default());
        for field in ["id", "contract_version", "name_key", "description_key"] {
            assert!(decl.contains(field), "missing field {field} in {decl}");
        }
    }
}
