//! Tool manifest: metadata the shell shows for a tool.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Stable metadata describing a hosted tool.
///
/// The manifest is the shell's single source of truth for what a tool is:
/// identity, version, i18n keys, icon, and route. It is produced by
/// [`crate::Tool::manifest`] and collected by
/// [`crate::ToolRegistry::manifests`].
///
/// The TypeScript mirror of this type lives in `packages/contracts`
/// (generated by ts-rs; see `docs/adr/0005-ts-rs-generated-contracts.md`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct ToolManifest {
    /// Unique, stable kebab-case identifier, e.g. `boq-inspector`.
    pub id: String,
    /// Tool contract version the tool targets; must equal
    /// [`crate::TOOL_CONTRACT_VERSION`] for the shell to host the tool.
    pub contract_version: u32,
    /// Semantic version of the tool itself, e.g. `"0.1.0"`. Independent of
    /// the contract version; bumped when the tool's behavior changes.
    pub tool_version: String,
    /// i18n key for the tool's display name.
    pub name_key: String,
    /// i18n key for the tool's one-line description.
    pub description_key: String,
    /// Icon reference (asset path or id) resolved by the shell.
    pub icon: String,
    /// Shell route the tool is mounted at, e.g. `/tools/boq-inspector`.
    pub route: String,
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;

    fn sample_manifest() -> ToolManifest {
        ToolManifest {
            id: "boq-inspector".to_string(),
            contract_version: crate::TOOL_CONTRACT_VERSION,
            tool_version: "0.1.0".to_string(),
            name_key: "tools.boq_inspector.name".to_string(),
            description_key: "tools.boq_inspector.description".to_string(),
            icon: "icons/boq-inspector.svg".to_string(),
            route: "/tools/boq-inspector".to_string(),
        }
    }

    #[test]
    fn manifest_serde_round_trip() {
        let manifest = sample_manifest();
        let json = serde_json::to_string(&manifest).expect("serializes");
        let back: ToolManifest = serde_json::from_str(&json).expect("deserializes");
        assert_eq!(manifest, back);
    }

    #[test]
    fn typescript_binding_contains_all_fields() {
        let decl = ToolManifest::decl(&ts_rs::Config::default());
        for field in [
            "id",
            "contract_version",
            "tool_version",
            "name_key",
            "description_key",
            "icon",
            "route",
        ] {
            assert!(decl.contains(field), "missing field {field} in {decl}");
        }
    }
}
